spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/FMH_DB
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    platform: postgres
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        format_sql: true
  flyway:
    locations: classpath:db/migration/dev
server:
  servlet:
    context-path: "/fmh"

logging.level.ru.iteco.fmh: debug
