spring:
  profiles:
    active: '@activatedProperties@'
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    format:
      date: iso
      date-time: iso
      time: iso
  flyway:
    validate-migration-naming: true
