spring:
  datasource:
    url: jdbc:tc:postgresql:12:///FMH_TEST
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  flyway:
    locations: classpath:db/migration/dev, classpath:db/migration/test
upload:
  path: ${DOCUMENTS_STATIC_PATH:./target/fmh/static/documents/}