spring:
  profiles:
    active: '@activatedProperties@'
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  flyway:
    validate-migration-naming: true
static-host:
  host: ${STATIC_HOST}