spring:
  profiles:
    active: '@activatedProperties@'
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  flyway:
    validate-migration-naming: true
  fmh:
    documents:
      static-storage: ${STATIC_HOST:localhost}