spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgresSQL95Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        format_sql: true
  flyway:
    locations: classpath:db/migration/dev
  sql:
    init:
      platform: postgres
server:
  servlet:
    context-path: /fmh

logging:
  level:
    ru.iteco.fmh: DEBUG

swagger:
  host: ${SWAGGER_HOST}
